# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      unlock:
        - 0x2D407dDb06311396fE14D4b49da5F0471447d45C  # Andre
        - 0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52  # Yearn Multisig
        - 0x3f5CE5FBFe3E9af3971dD833D26bA9b5C936f0bE  # Binance

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.5.17
    remappings:
      - "@openzeppelinV2=OpenZeppelin/openzeppelin-contracts@2.5.1"
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
